-- ============================================================================
-- N.E.X.U.S — Seed Data
-- ============================================================================
-- Intentionally left blank in the public release. Default agents
-- (claude/hermes/cursor/gemini) used to be auto-inserted here and in
-- 0004, but that locked every fresh install into "the team has these
-- four bots" — even when the operator had only one of the CLIs
-- installed. New default: no agents at install time. The operator
-- creates each bridge explicitly via:
--
--   make issue-invite USER=<name> CLI=<kind> CHANNELS=<...>
--
-- Existing installs with the old seeds are NOT affected — schema
-- migrations only run once (tracked in schema_migrations table). To
-- disable the old bots on an existing install:
--
--   UPDATE agents SET enabled = false WHERE kind = 'local';
--
-- Or delete them entirely once you're sure no transcripts reference them.
-- ============================================================================

INSERT INTO schema_migrations (version) VALUES ('0002_seed') ON CONFLICT DO NOTHING;
