#!/usr/bin/env bash
# ============================================================================
# install.sh — install the `nexus` CLI on your machine.
# ============================================================================
# Hosted at: https://kurniarahmattt.github.io/nexus/install.sh
#
# Usage:
#   curl -fsSL https://kurniarahmattt.github.io/nexus/install.sh | bash
#
# Or, if you want to inspect first (recommended):
#   curl -fsSL https://kurniarahmattt.github.io/nexus/install.sh -o install.sh
#   less install.sh
#   bash install.sh
#
# What it does:
#   1. Checks for Bun (Nexus's runtime). Offers to install if missing.
#   2. Downloads the latest nexus.js bundle to ~/.nexus/cli/nexus.js
#   3. Writes a small `nexus` wrapper script to ~/.local/bin/ (or
#      $NEXUS_PREFIX/bin/ if set)
#   4. Prints PATH instructions if the install dir isn't already on PATH
#
# Idempotent: re-running upgrades the bundle in place.
# ============================================================================

set -euo pipefail

# ---- pretty -----------------------------------------------------------------

if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'
  C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_CYAN=$'\033[36m'
else
  C_RESET=""; C_BOLD=""; C_DIM=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_CYAN=""
fi

ok()    { printf "${C_GREEN}✓${C_RESET} %s\n" "$*"; }
warn()  { printf "${C_YELLOW}!${C_RESET} %s\n" "$*"; }
err()   { printf "${C_RED}✗${C_RESET} %s\n" "$*" >&2; }
info()  { printf "${C_DIM}%s${C_RESET}\n" "$*"; }

# ---- where to install -------------------------------------------------------

NEXUS_PREFIX="${NEXUS_PREFIX:-$HOME/.local}"
NEXUS_HOME="${NEXUS_HOME:-$HOME/.nexus}"
BIN_DIR="${NEXUS_PREFIX}/bin"
CLI_DIR="${NEXUS_HOME}/cli"
BUNDLE_URL="${NEXUS_BUNDLE_URL:-https://kurniarahmattt.github.io/nexus/nexus.js}"

# ---- header -----------------------------------------------------------------

cat <<EOF

${C_BOLD}Installing the Nexus CLI${C_RESET}
${C_DIM}https://github.com/kurniarahmattt/nexus${C_RESET}

EOF

# ---- step 1: bun ------------------------------------------------------------

if command -v bun >/dev/null 2>&1; then
  ok "Bun $(bun --version) already installed"
else
  warn "Bun is not installed (Nexus runs on Bun)."
  if [ "${NEXUS_AUTO_INSTALL_BUN:-1}" = "1" ] && [ -t 0 ]; then
    printf "  ${C_CYAN}?${C_RESET} Install Bun now? [Y/n] "
    read -r ans
    case "${ans:-Y}" in
      n|N|no|NO)
        err "Bun is required. Install with: curl -fsSL https://bun.sh/install | bash"
        exit 1
        ;;
    esac
  fi
  info "running: curl -fsSL https://bun.sh/install | bash"
  curl -fsSL https://bun.sh/install | bash
  # Make Bun available in this shell for the rest of the install.
  if [ -d "$HOME/.bun/bin" ]; then
    export PATH="$HOME/.bun/bin:$PATH"
  fi
  if ! command -v bun >/dev/null 2>&1; then
    err "Bun installed, but `bun` is not on PATH. Restart your shell and re-run this installer."
    exit 1
  fi
  ok "Bun $(bun --version) installed"
fi

# ---- step 2: download bundle ------------------------------------------------

mkdir -p "$CLI_DIR" "$BIN_DIR"
BUNDLE_DEST="${CLI_DIR}/nexus.js"

info "fetching $BUNDLE_URL"
if ! curl -fsSL --max-time 60 "$BUNDLE_URL" -o "$BUNDLE_DEST.tmp"; then
  err "could not fetch the bundle from $BUNDLE_URL"
  echo "  Check your internet connection or set NEXUS_BUNDLE_URL to a reachable mirror."
  exit 1
fi
mv "$BUNDLE_DEST.tmp" "$BUNDLE_DEST"
ok "bundle saved to $BUNDLE_DEST ($(wc -c < "$BUNDLE_DEST" | tr -d ' ') bytes)"

# ---- step 3: write wrapper script ------------------------------------------

WRAPPER="${BIN_DIR}/nexus"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Nexus CLI launcher — generated by install.sh.
exec bun "${BUNDLE_DEST}" "\$@"
EOF
chmod +x "$WRAPPER"
ok "wrapper written to $WRAPPER"

# ---- step 4: PATH guidance --------------------------------------------------

if printf '%s' ":${PATH}:" | grep -q ":${BIN_DIR}:"; then
  ok "${BIN_DIR} is already on PATH"
else
  warn "${BIN_DIR} is NOT on PATH yet."
  shell_name=$(basename "${SHELL:-/bin/bash}")
  case "$shell_name" in
    zsh)  rc="$HOME/.zshrc";   line='export PATH="$HOME/.local/bin:$PATH"' ;;
    fish) rc="$HOME/.config/fish/config.fish"; line='set -gx PATH $HOME/.local/bin $PATH' ;;
    *)    rc="$HOME/.bashrc";  line='export PATH="$HOME/.local/bin:$PATH"' ;;
  esac
  echo
  echo "  Add this line to your shell rc and restart your shell:"
  echo "    ${C_CYAN}${line}${C_RESET}    ${C_DIM}# typically in ${rc}${C_RESET}"
  echo
fi

# ---- done -------------------------------------------------------------------

cat <<EOF

${C_GREEN}${C_BOLD}✓ Nexus CLI installed.${C_RESET}

  Try:
    ${C_CYAN}nexus help${C_RESET}

  Set up a host:
    ${C_CYAN}nexus host-onboard${C_RESET}

  Join an existing Nexus as a bridge:
    ${C_CYAN}nexus onboard${C_RESET}

  Documentation: ${C_CYAN}https://kurniarahmattt.github.io/nexus/${C_RESET}

EOF
